---
version: "3.3"
services:
  app:
    build: .
    ports:
      - 8082:8080
      - 50000:50000
    container_name: jenkins-docker
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge